### ISSUE TITLE
ARM64版无法在树莓派4B PI OS（64bit）启动

### ISSUE THREAD

**Issue by cylind** [maskedeken/gost-plugin#8]
我使用的是[gost-plugin-linux-arm64-v1.6.3@af4809e646.tar.gz](https://github.com/maskedeken/gost-plugin/releases/download/v1.6.3/gost-plugin-linux-arm64-v1.6.3@af4809e646.tar.gz)这个arm64版的插件，在aarch64架构的树莓派4b下配合shadowsocks-libev使用，软件报错如下：
```
$ ss-local  -l 1080 -s "server.com" -p 443 -k "password" -m "aes-256-gcm" --plugin "gost-plugin" --plugin-opts "mode=wws;path=/wspath;host=server.com;serverName=server.com"
 2023-10-16 11:09:45 INFO: plugin "gost-plugin" enabled
 2023-10-16 11:09:45 INFO: initializing ciphers... aes-256-gcm
 2023-10-16 11:09:45 INFO: listening at 127.0.0.1:1080
WARN[0000] [running in client mode]
FATA[0000] failed to create handler: [Transporter not found]
 2023-10-16 11:09:45 ERROR: plugin service exit unexpectedly
 2023-10-16 11:09:45 INFO: error on terminating the plugin.
```

**Comment by maskedeken** [comment]
> 我使用的是[gost-plugin-linux-arm64-v1.6.3@af4809e646.tar.gz](https://github.com/maskedeken/gost-plugin/releases/download/v1.6.3/gost-plugin-linux-arm64-v1.6.3@af4809e646.tar.gz)这个arm64版的插件，在aarch64架构的树莓派4b下配合shadowsocks-libev使用，软件报错如下：
> 
> ```
> $ ss-local  -l 1080 -s "server.com" -p 443 -k "password" -m "aes-256-gcm" --plugin "gost-plugin" --plugin-opts "mode=wws;path=/wspath;host=server.com;serverName=server.com"
>  2023-10-16 11:09:45 INFO: plugin "gost-plugin" enabled
>  2023-10-16 11:09:45 INFO: initializing ciphers... aes-256-gcm
>  2023-10-16 11:09:45 INFO: listening at 127.0.0.1:1080
> WARN[0000] [running in client mode]
> FATA[0000] failed to create handler: [Transporter not found]
>  2023-10-16 11:09:45 ERROR: plugin service exit unexpectedly
>  2023-10-16 11:09:45 INFO: error on terminating the plugin.
> ```

mode=wss，不是mode=wws

**Comment by cylind** [comment]
好的谢谢，确实是不小心打成wws了，改成wss后能正常使用了。
